### PR TITLE
Causal Loop with Polarities

### PR DESCRIPTION
**Pull request by neonWhiteout**
I'm far from satisfied with it, but it's taken long enough, need to get the ball rolling.

### CODE REVIEW

**Comment by neonWhiteout** [comment]
It should pass all tests at this point, though I commented out the one test for visualization's Graph_RB, will need to re-add that.

I don't think ordering edges such that all positive come before negative is great, but I'm not sure there's a better way to do it.

**Comment by neonWhiteout** [comment]
...Well, I'm scared to see why it's failing on the rewrite examples, as it works on my machine.

**Comment by neonWhiteout** [comment]
Catlab 0.16.16 breaks Rewrite.  Rewrite still works for 0.16.10.  I'd change the Project.toml so it doesn't use beyond Catlab 0.16.10 until we figure out how to fix it.

**Comment by neonWhiteout** [comment]
So at this point, I think Graph(seir_causalLoop) in examples/full_fledged_schema_examples/CaulsalLoopDiagrams/convert_from_SEIR_stockFlowDiagram.ipynb is broken because I'm having GraphCL work for graphing causal loops instead of Graph, and there's the whole Graph_RB thing that needs to have its test reintroduced.

**Comment by neonWhiteout** [comment]
I think from here I'd want to write a short markdown page with some documentation.

**Comment by neonWhiteout** [comment]
Ugh, why do I have both GraphSF and GraphF, which seem to be identical?  Will need to delete one of them.

**Comment by neonWhiteout** [comment]
We'll also want a function to return all shortest paths...

**Comment by neonWhiteout** [comment]
I should probably add a jupyter file showing all these functions off as well...

**Comment by neonWhiteout** [comment]
Dang, I didn't think the changes would break existing tests...

**Comment by neonWhiteout** [comment]
Yeah @Saityi @Xiaoyan-Li please have a look and confirm it looks good.

**Review by Saityi — APPROVED** [review]
Looks great! Nice work

I think we should consider a naming & cleaning pass through the entire library, giving consideration to what the initial version of the public consumption API could look like.

(Edit to add: In the future, not this pull request. 😅)

**Review by Saityi — APPROVED** [review]

**Comment by neonWhiteout** [comment]
> I think we should consider a naming & cleaning pass through the entire library, giving consideration to what the initial version of the public consumption API could look like.

I agree.  Also need a passover to ensure it adheres to Catlab formatting standards.

**Comment by neonWhiteout** [comment]
Ah damn commit didn't seem to merge correctly.

**Review by Xiaoyan-Li — APPROVED** [review]

**Pull request merged**
