### PR TITLE
Created @foot and @feet macros and added tests for them.

### PR DESCRIPTION
**Pull request by neonWhiteout**
Can now create a foot with (@foot A => B), or a vector of feet with 

@feet begin
A => B
C => ()
() => D
() => ()
end

### CODE REVIEW

**Comment by neonWhiteout** [comment]
Please note, right now this only works for feet with at most one stock and one sum variable

**Review by Saityi — COMMENTED** [review]
Overall this looks good to me; these are just some thoughts I had as I was reviewing it.

**Comment by neonWhiteout** [comment]
@Saityi 
> You could hypothetically rework this function to go all in on 'MLStyle.jl': @match can pattern match on julia expressions, e.g.
Agreed.  Looks way nicer that way.  I'm updating create_foot to use your notation.
> Should this be more like
Yes, it was a bad typo, thank you.
> re: note: Is this an intentional design choice?
At present, yes.  If I'd merge them, I'd want feet to return a vector of one element, so it always returns a vector of foots.  I can update it to do so.

**Comment by neonWhiteout** [comment]
Ok, hopefully it's alright.
Unsure if I'm satisfied with Expr(e, _...) =>, seems vague, and I'm not 100% that it'll catch everything.
I use @eval in three of the tests to make errors occur at runtime rather than compile time.
Mostly just incorporated your changes.

**Pull request merged**
