### PR TITLE
Add ternary operation in stockflow macro syntax

### PR DESCRIPTION
**Pull request by neonWhiteout**
Allows use of the syntax A = B ? C : D in a dynamic variable, where B, C and D can be symbols or expressions.  An expression of this form is converted into a function call cond(B,C,D) = B ? C : D

### CODE REVIEW

**Comment by neonWhiteout** [comment]
Probably wanna try actually running the differential equations on one of these.  If you have an example which uses an if else in another software, try porting it.

**Review by Saityi — APPROVED** [review]

**Comment by neonWhiteout** [comment]
@Saityi I did a few changes so || and && can be used as well.  Just convert A || B to or(A, B) := A || B and A && B to and(A,B) := A && B

**Comment by neonWhiteout** [comment]
> @Saityi I did a few changes so || and && can be used as well. Just convert A || B to or(A, B) := A || B and A && B to and(A,B) := A && B

...Which is stupid, because || and && only allow bools.  I guess we do:
or(A, B) := int(Bool(A) || Bool(B))

**Comment by neonWhiteout** [comment]
...No, no, it might still work, since A < B should return a bool

**Review by Saityi — APPROVED** [review]

**Pull request merged**
