### PR TITLE
CompatHelper: bump compat for Catlab to 0.16, (keep existing compat)

### PR DESCRIPTION
**Pull request by algebraicjuliabot**
This pull request changes the compat entry for the `Catlab` package from `0.15.5 - 0.16.7` to `0.15.5 - 0.16.7, 0.16`.
This keeps the compat entries for earlier versions.

Note: I have not tested your package with this new compat entry.
It is your responsibility to make sure that your package tests pass before you merge this pull request.

### CODE REVIEW

**Comment by neonWhiteout** [comment]
@Xiaoyan-Li @Saityi We're good to merge these compat helpers right

**Comment by Saityi** [comment]
@neonWhiteout The conflict needed to be resolved resolved; if the tests pass now, I think we'd be good to merge.

**Review by neonWhiteout — APPROVED** [review]
Looks good

**Comment by neonWhiteout** [comment]
@algebraicjuliabot register()

**Comment by neonWhiteout** [comment]
@JuliaRegistrator register()

**Pull request merged**
