### PR TITLE
Revert catlab version

### PR DESCRIPTION
**Pull request by neonWhiteout**
Added AlgebraicRewriting as a requirement, and specified it was less than version 2.0.

Added 

`
using Pkg; 
Pkg.activate("../../..") # Use StockFlow's Project.toml to ensure correct Catlab and AlgebraicRewriting versions
`

to the tops of the new examples.  Reverted Julia version requirements to be ≥ 1.7, rather than 1.9.

### CODE REVIEW

**Comment by neonWhiteout** [comment]
Also reverted import in StockFlow.jl to Catlab.Present

**Comment by neonWhiteout** [comment]
@Xiaoyan-Li Things should work here, if you wish to revert.
I'm unsure on what the proper way to enforce specific versions of packages.  It's possible the Pkg.activate("../../..") isn't necessary, but I needed it on my end.

**Comment by neonWhiteout** [comment]
Of course, the Pkg.activate("../../..") isn't going to work if the notebook is being run outside the project.

**Comment by Saityi** [comment]
>  I'm unsure on what the proper way to enforce specific versions of packages. It's possible the Pkg.activate("../../..") isn't necessary, but I needed it on my end. 

`Project.toml` handles that. What I think you're running into is that -- until this is merged -- `add StockFlow` pulls in the main branch version and doesn't test this out. To test this, point `Pkg` at your branch:

``` bash
(@v1.9) pkg> add https://github.com/neonWhiteout/StockFlow.jl.git#revert_catlab_version
    Updating git-repo `https://github.com/neonWhiteout/StockFlow.jl.git`
   Resolving package versions...
    Updating `~/.julia/environments/v1.9/Project.toml`
  [58c4a0e8] ~ StockFlow v0.1.0 ⇒ v0.1.0 `https://github.com/neonWhiteout/StockFlow.jl.git#revert_catlab_version`
    Updating `~/.julia/environments/v1.9/Manifest.toml`
[...]

(@v1.9) pkg> add Catlab
   Resolving package versions...
    Updating `~/.julia/environments/v1.9/Project.toml`
⌅ [134e5e36] + Catlab v0.14.17

julia> Pkg.installed()["Catlab"]
┌ Warning: Pkg.installed() is deprecated
└ @ Pkg ~/.julia/juliaup/julia-1.9.1+0.x64.linux.gnu/share/julia/stdlib/v1.9/Pkg/src/Pkg.jl:726
v"0.14.17"

(@v1.9) pkg> add StockFlow#master
    Updating git-repo `https://github.com/neonWhiteout/StockFlow.jl.git`
   Resolving package versions...
   Installed ACSets ─ v0.2.5
   Installed Catlab ─ v0.15.4
    Updating `~/.julia/environments/v1.9/Project.toml`
  [134e5e36] ↑ Catlab v0.14.17 ⇒ v0.15.4
```

**Comment by neonWhiteout** [comment]
Haven't tested it yet, but should be able to close this once https://github.com/AlgebraicJulia/Catlab.jl/pull/839 gets accepted

**Comment by neonWhiteout** [comment]
New Catlab patch fixes this, no need to revert.

**Pull request closed without merging**
