### PR TITLE
Run Jupyter notebook examples in Github Actions as a sanity check on changes

### PR DESCRIPTION
**Pull request by Saityi**
## Issue

We cannot currently detect when changes in the library break important features used by the notebook examples.

## Changes

Add a step to continuous integration that installs IJulia, then runs three representative notebooks (one composition, one stratification, and another); if any throws an exception (e.g. due to a changed import or API change) the build fails.

The new workflow uses [yaananth/run-notebook](https://github.com/yaananth/run-notebook) to run the notebooks.

@Xiaoyan-Li

### CODE REVIEW

**Comment by neonWhiteout** [comment]
Is there any way to cache the Julia compilation, and only compile StockFlow?

Could try removing some requirements, too, but I dunno if there'd be much success with that.

**Comment by Saityi** [comment]
> Is there any way to cache the Julia compilation, and only compile StockFlow?

Sorry, I think I understand your question, and I think it's coming from the phrase 'most of which is precompiling Julia'; that was not the thing I meant to say. Instead I meant to say: most of that 15 minutes is spent precompiling _`StockFlow.jl` and its dependencies_, not compiling 'Julia'. My apologies!

What I was seeing was that notebooks appear to need a full precompile of `StockFlow.jl` and its dependencies before running, like you'd get from `Pkg.precompile()`. If `Pkg.precompile()` wasn't performed before running the notebook, running the notebook caused a precompile anyways.

The few times I was successful in caching the precompilation artifacts, something else would break like `IJulia` when the cache was used (the notebook would complain of not finding the julia kernel), while the precompile time confusingly happened anyways.

> Could try removing some requirements, too, but I dunno if there'd be much success with that.

I think it'd certainly help speed up the example checking if there are any dependencies we could remove, especially if we're depending on a large but unused library. I'll have to look into it (unless ya'll know a tool for detecting unused deps?).

**Comment by neonWhiteout** [comment]
Ran grep a few times on the folder for some dependency names I haven't seen much of

Combinatorics is only imported in PrimitiveStockFlowInPaper.jl, don't know what it's used for, if anything.
CompTime isn't anywhere
Graphviz_jll isn't anywhere
JSON isn't anywhere
LinearAlgebra isn't anywhere
StaticArrays data types show up in a few papers, but it's never imported; maybe comes from Catlab?
StatsBase is only imported in visualization.jl, don't know what it's used for, if anything.
StringManipulation isn't anywhere
Tables isn't anywhere


@Xiaoyan-Li would need to say if any of these are important, but we can probably cut a lot of them.

**Comment by neonWhiteout** [comment]
Nevermind looks like all the things I listed are dependencies for the other packages we import

**Comment by neonWhiteout** [comment]
Had an idea; we could try multithreading the tests.

**Comment by Xiaoyan-Li** [comment]
I remember Eric mentioned he has the same problem in Modellab when it calls the julia code and run the models. Probably we can double check with him does he has better idea to solve the precompile problem.

**Comment by Saityi** [comment]
> Had an idea; we could try multithreading the tests.

If we ran all three notebooks at the same time, hypothetically the upper bound of runtime is the longest one (4m 19s), ignoring resource allocation difficulties. The question would be, how do we multithread the notebook running? 

We could run separate github actions jobs, but then each would have its own compilation. Instead of one 16 minute build, we instead would have three 14-16 minute builds, one per notebook. Unfortunately, as far as I know, you can't say 'up to this point is a single build, but then these steps, run in parallel' with github actions.

We could manually run them in a multithreaded way, but I've experienced builds like that in the past, and you often get very confusing output, and tracking down errors isn't always easy. The output needs to be sensibly captured from each runner in some way and then turned into a single log (elsewise you have a bunch of different builds all weaving their logs in and out of each other).

Since this is merged, I think what I'll do is file an issue for future improvements in the regression test area covering these and linking this PR.

**Pull request merged**
