### PR TITLE
Reran new models after Catlab update.  

### PR DESCRIPTION
**Pull request by neonWhiteout**
Fixed sir_standard_stratification with a different hom import, renamed a variable in sir_linear_stratification.  Overall, things worked pretty well.

In second commit, reran original examples.  Had to do Graph = StockFlow.Graph a few times, as Catlab had a Graph which interfered.  Fixed a few typos, converted a few comments to markdown.

All examples should be ok at this point.

### CODE REVIEW

**Comment by neonWhiteout** [comment]
@Xiaoyan-Li Please have a look.  Example models all work here.

**Comment by Xiaoyan-Li** [comment]
> @Xiaoyan-Li Please have a look. Example models all work here.

Thank you very much!! The examples all look great!

Only have a quick question: What is the difference between the two examples: diabetes_diagnose and sir_linear... seems are all about the diabetes stratified models? Should we combine those two examples to be one? Or at least I may suggest modify the "sir_linear... " example's name to be "diabetes_linear...".

**Comment by neonWhiteout** [comment]
The sir linear and sir standard came from your paper, the diabetes model was one which already existed.  It's possible they're the same.

**Comment by neonWhiteout** [comment]
Will hopefully be good after this... need to let tests finish and see, though

**Comment by neonWhiteout** [comment]
Ok looks good

**Pull request merged**
